In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy as sp 

In [47]:
male_df = pd.read_csv('./fifa_2022/players_22.csv')

/Users/admin/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (25,108) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


In [48]:
male_df.dtypes

sofifa_id            int64
player_url          object
short_name          object
long_name           object
player_positions    object
                     ...  
player_face_url     object
club_logo_url       object
club_flag_url       object
nation_logo_url     object
nation_flag_url     object
Length: 110, dtype: object

In [5]:
male_df.shape

(19239, 110)

In [6]:
male_df.head(2)

sofifa_id                                         player_url  \
0     158023  https://sofifa.com/player/158023/lionel-messi/...   
1     188545  https://sofifa.com/player/188545/robert-lewand...   

       short_name                       long_name player_positions  overall  \
0        L. Messi  Lionel Andrés Messi Cuccittini       RW, ST, CF       93   
1  R. Lewandowski              Robert Lewandowski               ST       92   

   potential    value_eur  wage_eur  age  ...   lcb    cb   rcb    rb    gk  \
0         93   78000000.0  320000.0   34  ...  50+3  50+3  50+3  61+3  19+3   
1         92  119500000.0  270000.0   32  ...  60+3  60+3  60+3  61+3  19+3   

                                     player_face_url  \
0  https://cdn.sofifa.net/players/158/023/22_120.png   
1  https://cdn.sofifa.net/players/188/545/22_120.png   

                            club_logo_url  \
0  https://cdn.sofifa.net/teams/73/60.png   
1  https://cdn.sofifa.net/teams/21/60.png   

                         club_flag_url  \
0  https://cdn.sofifa.net/flags/fr.png   
1  https://cdn.sofifa.net/flags/de.png   

                            nation_logo_url  \
0  https://cdn.sofifa.net/teams/1369/60.png   
1  https://cdn.sofifa.net/teams/1353/60.png   

                       nation_flag_url  
0  https://cdn.sofifa.net/flags/ar.png  
1  https://cdn.sofifa.net/flags/pl.png  

[2 rows x 110 columns]

### eliminamos columnas inutiles

#### 1 - eliminar columnas con url

In [49]:
male_df.drop(['player_face_url','player_url','club_logo_url','club_flag_url','nation_logo_url','nation_flag_url'],axis=1,inplace=True)

In [50]:
for i in male_df.columns:
    if i.__contains__('url'):
        print(i)

In [51]:
for i in male_df.columns:
    print(i)

sofifa_id
short_name
long_name
player_positions
overall
potential
value_eur
wage_eur
age
dob
height_cm
weight_kg
club_team_id
club_name
league_name
league_level
club_position
club_jersey_number
club_loaned_from
club_joined
club_contract_valid_until
nationality_id
nationality_name
nation_team_id
nation_position
nation_jersey_number
preferred_foot
weak_foot
skill_moves
international_reputation
work_rate
body_type
real_face
release_clause_eur
player_tags
player_traits
pace
shooting
passing
dribbling
defending
physic
attacking_crossing
attacking_finishing
attacking_heading_accuracy
attacking_short_passing
attacking_volleys
skill_dribbling
skill_curve
skill_fk_accuracy
skill_long_passing
skill_ball_control
movement_acceleration
movement_sprint_speed
movement_agility
movement_reactions
movement_balance
power_shot_power
power_jumping
power_stamina
power_strength
power_long_shots
mentality_aggression
mentality_interceptions
mentality_positioning
mentality_vision
mentality_penalties
mentality_c

### usamos columna sofifa_id como indice del dataframe

In [52]:
male_df.set_index('sofifa_id',drop=True,inplace=True)

#### Resumen de abreviaciones de posiciones

GK - Goalkeeper

RB - Right Back

RWB - Right Wing Back

CB - Centre Back

LWB - Left Wing Back

LB - Left Back

CM - Centre Mid

CDM - Centre Defensive Mid

CAM - Centre Attacking Mid

RM - Right Mid

LM - Left Mid

LW - Left Wing

RW - Right Wing

CF - Centre Forward

LF - Left Forward

RF - Right Forward

ST - Striker



In [10]:
male_df[[
    'short_name','ls',
'st',
'rs',
'lw',
'lf',
'cf',
'rf',
'rw',
'lam',
'cam',
'ram',
'lm',
'lcm',
'cm',
'rcm',
'rm',
'lwb',
'ldm',
'cdm',
'rdm',
'rwb',
'lb',
'lcb',
'cb',
'rcb',
'rb',
'gk']]

short_name    ls    st    rs  lw  lf  cf  rf  rw   lam  \
sofifa_id                                                                   
158023               L. Messi  89+3  89+3  89+3  92  93  93  93  92    93   
188545         R. Lewandowski  90+2  90+2  90+2  85  88  88  88  85  86+3   
20801       Cristiano Ronaldo  90+1  90+1  90+1  88  89  89  89  88  86+3   
190871              Neymar Jr  83+3  83+3  83+3  90  88  88  88  90  89+2   
192985           K. De Bruyne  83+3  83+3  83+3  88  87  87  87  88  89+2   
...                       ...   ...   ...   ...  ..  ..  ..  ..  ..   ...   
261962              Song Defu  44+2  44+2  44+2  46  45  45  45  46  46+2   
262040              C. Porter  45+2  45+2  45+2  47  46  46  46  47  47+2   
262760               N. Logue  45+2  45+2  45+2  46  46  46  46  46  47+2   
262820              L. Rudden  47+2  47+2  47+2  47  47  47  47  47  45+2   
264540     E. Lalchhanchhuaha  45+2  45+2  45+2  47  47  47  47  47  47+2   

           ...   ldm   cdm   rdm   rwb    lb   lcb    cb   rcb    rb    gk  
sofifa_id  ...                                                              
158023     ...  64+3  64+3  64+3  66+3  61+3  50+3  50+3  50+3  61+3  19+3  
188545     ...  66+3  66+3  66+3  64+3  61+3  60+3  60+3  60+3  61+3  19+3  
20801      ...  59+3  59+3  59+3  63+3  60+3  53+3  53+3  53+3  60+3  20+3  
190871     ...  63+3  63+3  63+3  67+3  62+3  50+3  50+3  50+3  62+3  20+3  
192985     ...  80+3  80+3  80+3  79+3  75+3  69+3  69+3  69+3  75+3  21+3  
...        ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  
261962     ...  46+2  46+2  46+2  48+2  48+2  46+2  46+2  46+2  48+2  15+2  
262040     ...  46+2  46+2  46+2  49+2  48+2  44+2  44+2  44+2  48+2  14+2  
262760     ...  46+2  46+2  46+2  47+2  47+2  45+2  45+2  45+2  47+2  12+2  
262820     ...  29+2  29+2  29+2  33+2  32+2  26+2  26+2  26+2  32+2  15+2  
264540     ...  44+2  44+2  44+2  45+2  45+2  41+2  41+2  41+2  45+2  16+2  

[19239 rows x 28 columns]

In [19]:
male_df[male_df.short_name=='L. Messi']

short_name                       long_name player_positions  \
sofifa_id                                                               
158023      L. Messi  Lionel Andrés Messi Cuccittini       RW, ST, CF   

           overall  potential   value_eur  wage_eur  age         dob  \
sofifa_id                                                              
158023          93         93  78000000.0  320000.0   34  1987-06-24   

           height_cm  ...   ldm   cdm   rdm   rwb    lb   lcb    cb   rcb  \
sofifa_id             ...                                                   
158023           170  ...  64+3  64+3  64+3  66+3  61+3  50+3  50+3  50+3   

             rb    gk  
sofifa_id              
158023     61+3  19+3  

[1 rows x 103 columns]

#### crear nuevas columnas con "+" que contengan el numero añadido - PDTE 

### buscar todos los jugadores de una misma selección para comparar sus stats

### en nuestro caso: Francia

In [11]:
male_df[(male_df.short_name == 'K. Mbappé') | (male_df.short_name == "N. Kanté") |
       (male_df.short_name == "P. Pogba") | (male_df.short_name == "A. Griezmann") |
       (male_df.short_name == "K. Benzema") | (male_df.short_name == "O. Dembélé") |
       (male_df.short_name == "B. Pavard") | (male_df.short_name == "H. Lloris") |
       (male_df.short_name == "D. Upamecano")][['short_name','ls',
'st',
'rs',
'lw',
'lf',
'cf',
'rf',
'rw',
'lam',
'cam',
'ram',
'lm',
'lcm',
'cm',
'rcm',
'rm',
'lwb',
'ldm',
'cdm',
'rdm',
'rwb',
'lb',
'lcb',
'cb',
'rcb',
'rb',
'gk']]

short_name    ls    st    rs  lw    lf    cf    rf  rw   lam  \
sofifa_id                                                                   
231747        K. Mbappé  89+3  89+3  89+3  90    90    90    90  90  89+3   
215914         N. Kanté  72+3  72+3  72+3  77    77    77    77  77  78+3   
165153       K. Benzema  87+2  87+2  87+2  85    87    87    87  85  86+3   
167948        H. Lloris  31+3  31+3  31+3  33    34    34    34  33  38+3   
195864         P. Pogba  82+3  82+3  82+3  82    83    83    83  82  85+2   
194765     A. Griezmann  84+1  84+1  84+1  85  86-1  86-1  86-1  85  86-1   
231443       O. Dembélé  76+3  76+3  76+3  83    81    81    81  83  81+3   
229558     D. Upamecano  62+2  62+2  62+2  63    63    63    63  63  64+2   
226851        B. Pavard  66+3  66+3  66+3  67    66    66    66  67  68+3   

           ...   ldm   cdm   rdm   rwb    lb   lcb    cb   rcb    rb    gk  
sofifa_id  ...                                                              
231747     ...  63+3  63+3  63+3  67+3  63+3  54+3  54+3  54+3  63+3  18+3  
215914     ...  87+3  87+3  87+3  85+3  85+3  84+3  84+3  84+3  85+3  20+3  
165153     ...  62+3  62+3  62+3  63+3  59+3  55+3  55+3  55+3  59+3  18+3  
167948     ...  38+3  38+3  38+3  35+3  34+3  30+3  30+3  30+3  34+3  85+2  
195864     ...  78+3  78+3  78+3  74+3  72+3  72+3  72+3  72+3  72+3  13+3  
194765     ...  69+3  69+3  69+3  71+3  69+3  63+3  63+3  63+3  69+3  21+3  
231443     ...  58+3  58+3  58+3  63+3  59+3  47+3  47+3  47+3  59+3  17+3  
229558     ...  76+2  76+2  76+2  74+2  76+2  82+2  82+2  82+2  76+2  17+2  
226851     ...  76+3  76+3  76+3  76+3  77+3  77+3  77+3  77+3  77+3  17+3  

[9 rows x 28 columns]

In [12]:
male_21_df = pd.read_csv('./fifa_2022/players_21.csv')

In [13]:
male_21_df[(male_21_df.short_name == 'K. Mbappé') | (male_21_df.short_name == "N. Kanté") |
       (male_21_df.short_name == "P. Pogba") | (male_21_df.short_name == "A. Griezmann") |
       (male_21_df.short_name == "K. Benzema") | (male_21_df.short_name == "O. Dembélé") |
       (male_21_df.short_name == "B. Pavard") | (male_21_df.short_name == "H. Lloris") |
       (male_21_df.short_name == "D. Upamecano")][['short_name','ls',
'st',
'rs',
'lw',
'lf',
'cf',
'rf',
'rw',
'lam',
'cam',
'ram',
'lm',
'lcm',
'cm',
'rcm',
'rm',
'lwb',
'ldm',
'cdm',
'rdm',
'rwb',
'lb',
'lcb',
'cb',
'rcb',
'rb',
'gk']]

short_name    ls    st    rs  lw  lf  cf  rf  rw   lam  ...   ldm  \
11      K. Mbappé  88+3  88+3  88+3  89  89  89  89  89  87+3  ...  63+3   
14     K. Benzema  86+3  86+3  86+3  85  87  87  87  85  86+3  ...  63+3   
27       N. Kanté  72+3  72+3  72+3  77  77  77  77  77  79+3  ...  86+2   
29      H. Lloris  31+3  31+3  31+3  32  33  33  33  32  35+3  ...  37+3   
38   A. Griezmann  85+2  85+2  85+2  86  86  86  86  86  86+1  ...  71+3   
57       P. Pogba  82+3  82+3  82+3  82  83  83  83  82  84+3  ...  78+3   
209    O. Dembélé  76+3  76+3  76+3  83  81  81  81  83  81+3  ...  58+3   
343     B. Pavard  66+2  66+2  66+2  68  67  67  67  68  69+2  ...  79+2   
644  D. Upamecano  60+2  60+2  60+2  60  60  60  60  60  62+2  ...  74+2   

      cdm   rdm   rwb    lb   lcb    cb   rcb    rb    gk  
11   63+3  63+3  67+3  63+3  55+3  55+3  55+3  63+3  18+3  
14   63+3  63+3  63+3  59+3  55+3  55+3  55+3  59+3  18+3  
27   86+2  86+2  85+3  84+3  83+3  83+3  83+3  84+3  20+3  
29   37+3  37+3  35+3  34+3  30+3  30+3  30+3  34+3  85+2  
38   71+3  71+3  73+3  70+3  65+3  65+3  65+3  70+3  21+3  
57   78+3  78+3  76+3  74+3  73+3  73+3  73+3  74+3  13+3  
209  58+3  58+3  63+3  59+3  47+3  47+3  47+3  59+3  17+3  
343  79+2  79+2  78+2  79+2  80+2  80+2  80+2  79+2  18+2  
644  74+2  74+2  70+2  72+2  79+2  79+2  79+2  72+2  16+2  

[9 rows x 28 columns]

### DESCR de columnas
- short_name object
- long_name object
- player_positions object
- overall int64
- potential int64
- value_eur float64
- wage_eur float64
- age int64
- dob object
- height_cm int64
- weight_kg int64
- club_team_id float64
- club_name object
- league_name object
- league_level float64
- club_position object
- club_jersey_number float64
- club_loaned_from object
- club_joined object
- club_contract_valid_until float64
- nationality_id int64
- nationality_name object
- nation_team_id float64
- nation_position object
- nation_jersey_number float64
- preferred_foot object
- weak_foot int64
- skill_moves int64
- international_reputation int64
- work_rate object
- body_type object
- real_face object
- release_clause_eur float64
- player_tags object
- player_traits object
- pace float64
- shooting float64
- passing float64
- dribbling float64
- defending float64
- physic float64
- attacking_crossing int64
- attacking_finishing int64
- attacking_heading_accuracy int64
- attacking_short_passing int64
- attacking_volleys int64
- skill_dribbling int64
- skill_curve int64
- skill_fk_accuracy int64
- skill_long_passing int64
- skill_ball_control int64
- movement_acceleration int64
- movement_sprint_speed int64
- movement_agility int64
- movement_reactions int64
- movement_balance int64
- power_shot_power int64
- power_jumping int64
- power_stamina int64
- power_strength int64
- power_long_shots int64
- mentality_aggression int64
- mentality_interceptions int64
- mentality_positioning int64
- mentality_vision int64
- mentality_penalties int64
- mentality_composure int64
- defending_marking_awareness int64
- defending_standing_tackle int64
- defending_sliding_tackle int64
- goalkeeping_diving int64
- goalkeeping_handling int64
- goalkeeping_kicking int64
- goalkeeping_positioning int64
- goalkeeping_reflexes int64
- goalkeeping_speed float64

In [14]:
for i,j in male_df.dtypes.iteritems():
    print(i,j)

short_name object
long_name object
player_positions object
overall int64
potential int64
value_eur float64
wage_eur float64
age int64
dob object
height_cm int64
weight_kg int64
club_team_id float64
club_name object
league_name object
league_level float64
club_position object
club_jersey_number float64
club_loaned_from object
club_joined object
club_contract_valid_until float64
nationality_id int64
nationality_name object
nation_team_id float64
nation_position object
nation_jersey_number float64
preferred_foot object
weak_foot int64
skill_moves int64
international_reputation int64
work_rate object
body_type object
real_face object
release_clause_eur float64
player_tags object
player_traits object
pace float64
shooting float64
passing float64
dribbling float64
defending float64
physic float64
attacking_crossing int64
attacking_finishing int64
attacking_heading_accuracy int64
attacking_short_passing int64
attacking_volleys int64
skill_dribbling int64
skill_curve int64
skill_fk_accuracy in

In [15]:
male_df.drop(['long_name'],axis=1)

short_name player_positions  overall  potential  \
sofifa_id                                                            
158023               L. Messi       RW, ST, CF       93         93   
188545         R. Lewandowski               ST       92         92   
20801       Cristiano Ronaldo           ST, LW       91         91   
190871              Neymar Jr          LW, CAM       91         91   
192985           K. De Bruyne          CM, CAM       91         91   
...                       ...              ...      ...        ...   
261962              Song Defu              CDM       47         52   
262040              C. Porter               CM       47         59   
262760               N. Logue               CM       47         55   
262820              L. Rudden               ST       47         60   
264540     E. Lalchhanchhuaha              CAM       47         60   

             value_eur  wage_eur  age         dob  height_cm  weight_kg  ...  \
sofifa_id                                                                ...   
158023      78000000.0  320000.0   34  1987-06-24        170         72  ...   
188545     119500000.0  270000.0   32  1988-08-21        185         81  ...   
20801       45000000.0  270000.0   36  1985-02-05        187         83  ...   
190871     129000000.0  270000.0   29  1992-02-05        175         68  ...   
192985     125500000.0  350000.0   30  1991-06-28        181         70  ...   
...                ...       ...  ...         ...        ...        ...  ...   
261962         70000.0    1000.0   22  1999-01-02        180         64  ...   
262040        110000.0     500.0   19  2002-03-18        175         70  ...   
262760        100000.0     500.0   21  2000-02-07        178         72  ...   
262820        110000.0     500.0   19  2002-04-23        173         66  ...   
264540        110000.0     500.0   19  2002-02-06        167         61  ...   

            ldm   cdm   rdm   rwb    lb   lcb    cb   rcb    rb    gk  
sofifa_id                                                              
158023     64+3  64+3  64+3  66+3  61+3  50+3  50+3  50+3  61+3  19+3  
188545     66+3  66+3  66+3  64+3  61+3  60+3  60+3  60+3  61+3  19+3  
20801      59+3  59+3  59+3  63+3  60+3  53+3  53+3  53+3  60+3  20+3  
190871     63+3  63+3  63+3  67+3  62+3  50+3  50+3  50+3  62+3  20+3  
192985     80+3  80+3  80+3  79+3  75+3  69+3  69+3  69+3  75+3  21+3  
...         ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  
261962     46+2  46+2  46+2  48+2  48+2  46+2  46+2  46+2  48+2  15+2  
262040     46+2  46+2  46+2  49+2  48+2  44+2  44+2  44+2  48+2  14+2  
262760     46+2  46+2  46+2  47+2  47+2  45+2  45+2  45+2  47+2  12+2  
262820     29+2  29+2  29+2  33+2  32+2  26+2  26+2  26+2  32+2  15+2  
264540     44+2  44+2  44+2  45+2  45+2  41+2  41+2  41+2  45+2  16+2  

[19239 rows x 102 columns]

#### buscar relación entre potential y overall. Predicción de quien puede mejorar PDTE

In [16]:
male_df[['potential','overall']]

potential  overall
sofifa_id                    
158023            93       93
188545            92       92
20801             91       91
190871            91       91
192985            91       91
...              ...      ...
261962            52       47
262040            59       47
262760            55       47
262820            60       47
264540            60       47

[19239 rows x 2 columns]

In [17]:
male_df[['short_name','value_eur','wage_eur']]

short_name    value_eur  wage_eur
sofifa_id                                           
158023               L. Messi   78000000.0  320000.0
188545         R. Lewandowski  119500000.0  270000.0
20801       Cristiano Ronaldo   45000000.0  270000.0
190871              Neymar Jr  129000000.0  270000.0
192985           K. De Bruyne  125500000.0  350000.0
...                       ...          ...       ...
261962              Song Defu      70000.0    1000.0
262040              C. Porter     110000.0     500.0
262760               N. Logue     100000.0     500.0
262820              L. Rudden     110000.0     500.0
264540     E. Lalchhanchhuaha     110000.0     500.0

[19239 rows x 3 columns]

In [18]:
#comentario random

### revisar csv career

In [21]:
df_career = pd.read_excel('./fifa_2022/Career Mode player datasets - FIFA 15-22.xlsx')

In [22]:
df_career.head(5)

sofifa_id                                         player_url  \
0     158023  https://sofifa.com/player/158023/lionel-messi/...   
1      20801  https://sofifa.com/player/20801/c-ronaldo-dos-...   
2       9014  https://sofifa.com/player/9014/arjen-robben/15...   
3      41236  https://sofifa.com/player/41236/zlatan-ibrahim...   
4     167495  https://sofifa.com/player/167495/manuel-neuer/...   

          short_name                            long_name player_positions  \
0           L. Messi       Lionel Andrés Messi Cuccittini               CF   
1  Cristiano Ronaldo  Cristiano Ronaldo dos Santos Aveiro           LW, LM   
2          A. Robben                         Arjen Robben       RM, LM, RW   
3     Z. Ibrahimović                   Zlatan Ibrahimović               ST   
4           M. Neuer                   Manuel Peter Neuer               GK   

   overall  potential    value_eur  wage_eur  age  ...   lcb    cb   rcb  \
0       93         95  100500000.0  550000.0   27  ...  45+3  45+3  45+3   
1       92         92   79000000.0  375000.0   29  ...  52+3  52+3  52+3   
2       90         90   54500000.0  275000.0   30  ...  46+3  46+3  46+3   
3       90         90   52500000.0  275000.0   32  ...  55+3  55+3  55+3   
4       90         90   63500000.0  300000.0   28  ...  38+3  38+3  38+3   

     rb    gk                                    player_face_url  \
0  54+3  15+3  https://cdn.sofifa.net/players/158/023/15_120.png   
1  57+3  16+3  https://cdn.sofifa.net/players/020/801/15_120.png   
2  55+3  14+3  https://cdn.sofifa.net/players/009/014/15_120.png   
3  56+3  17+3  https://cdn.sofifa.net/players/041/236/15_120.png   
4  36+3  87+3  https://cdn.sofifa.net/players/167/495/15_120.png   

                             club_logo_url  \
0  https://cdn.sofifa.net/teams/241/60.png   
1  https://cdn.sofifa.net/teams/243/60.png   
2   https://cdn.sofifa.net/teams/21/60.png   
3   https://cdn.sofifa.net/teams/73/60.png   
4   https://cdn.sofifa.net/teams/21/60.png   

                         club_flag_url  \
0  https://cdn.sofifa.net/flags/es.png   
1  https://cdn.sofifa.net/flags/es.png   
2  https://cdn.sofifa.net/flags/de.png   
3  https://cdn.sofifa.net/flags/fr.png   
4  https://cdn.sofifa.net/flags/de.png   

                              nation_logo_url  \
0    https://cdn.sofifa.net/teams/1369/60.png   
1    https://cdn.sofifa.net/teams/1354/60.png   
2  https://cdn.sofifa.net/teams/105035/60.png   
3    https://cdn.sofifa.net/teams/1363/60.png   
4    https://cdn.sofifa.net/teams/1337/60.png   

                       nation_flag_url  
0  https://cdn.sofifa.net/flags/ar.png  
1  https://cdn.sofifa.net/flags/pt.png  
2  https://cdn.sofifa.net/flags/nl.png  
3  https://cdn.sofifa.net/flags/se.png  
4  https://cdn.sofifa.net/flags/de.png  

[5 rows x 110 columns]

In [26]:
df_career.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16155 entries, 0 to 16154
Columns: 110 entries, sofifa_id to nation_flag_url
dtypes: datetime64[ns](2), float64(17), int64(43), object(48)
memory usage: 13.6+ MB


In [29]:
colu = df_career.columns

In [31]:
for i in colu:
    print(i)

sofifa_id
player_url
short_name
long_name
player_positions
overall
potential
value_eur
wage_eur
age
dob
height_cm
weight_kg
club_team_id
club_name
league_name
league_level
club_position
club_jersey_number
club_loaned_from
club_joined
club_contract_valid_until
nationality_id
nationality_name
nation_team_id
nation_position
nation_jersey_number
preferred_foot
weak_foot
skill_moves
international_reputation
work_rate
body_type
real_face
release_clause_eur
player_tags
player_traits
pace
shooting
passing
dribbling
defending
physic
attacking_crossing
attacking_finishing
attacking_heading_accuracy
attacking_short_passing
attacking_volleys
skill_dribbling
skill_curve
skill_fk_accuracy
skill_long_passing
skill_ball_control
movement_acceleration
movement_sprint_speed
movement_agility
movement_reactions
movement_balance
power_shot_power
power_jumping
power_stamina
power_strength
power_long_shots
mentality_aggression
mentality_interceptions
mentality_positioning
mentality_vision
mentality_penalties


In [32]:
len(male_df.columns)

103

In [41]:
rows = [26,51,76,103]

In [42]:
collaborators = ['gerard','kseniya','akram','adriana']

In [43]:
row = 0
for i in rows:
    p = np.random.choice(collaborators)
    collaborators.remove(p)
    print(f'{p} has to do rows from {row} to {i}')
    row = i

gerard has to do rows from 0 to 26
kseniya has to do rows from 26 to 51
akram has to do rows from 51 to 76
adriana has to do rows from 76 to 103


### Columns from 26 to 51

In [53]:
male_df.iloc[:,26:51]

weak_foot  skill_moves  international_reputation      work_rate  \
sofifa_id                                                                    
158023             4            4                         5     Medium/Low   
188545             4            4                         5    High/Medium   
20801              4            5                         5       High/Low   
190871             5            5                         5    High/Medium   
192985             5            4                         4      High/High   
...              ...          ...                       ...            ...   
261962             3            2                         1  Medium/Medium   
262040             3            2                         1  Medium/Medium   
262760             3            2                         1  Medium/Medium   
262820             3            2                         1  Medium/Medium   
264540             3            2                         1  Medium/Medium   

                body_type real_face  release_clause_eur  \
sofifa_id                                                 
158023             Unique       Yes         144300000.0   
188545             Unique       Yes         197200000.0   
20801              Unique       Yes          83300000.0   
190871             Unique       Yes         238700000.0   
192985             Unique       Yes         232200000.0   
...                   ...       ...                 ...   
261962     Lean (170-185)        No            114000.0   
262040     Lean (170-185)        No            193000.0   
262760     Lean (170-185)        No            175000.0   
262820     Lean (170-185)        No            239000.0   
264540        Lean (170-)        No            217000.0   

                                                 player_tags  \
sofifa_id                                                      
158023     #Dribbler, #Distance Shooter, #FK Specialist, ...   
188545     #Aerial Threat, #Distance Shooter, #Clinical F...   
20801      #Aerial Threat, #Dribbler, #Distance Shooter, ...   
190871     #Speedster, #Dribbler, #Playmaker, #FK Special...   
192985     #Dribbler, #Playmaker, #Engine, #Distance Shoo...   
...                                                      ...   
261962                                                   NaN   
262040                                                   NaN   
262760                                                   NaN   
262820                                                   NaN   
264540                                                   NaN   

                                               player_traits  pace  ...  \
sofifa_id                                                           ...   
158023     Finesse Shot, Long Shot Taker (AI), Playmaker ...  85.0  ...   
188545     Solid Player, Finesse Shot, Outside Foot Shot,...  78.0  ...   
20801      Power Free-Kick, Flair, Long Shot Taker (AI), ...  87.0  ...   
190871     Injury Prone, Flair, Speed Dribbler (AI), Play...  91.0  ...   
192985     Injury Prone, Leadership, Early Crosser, Long ...  76.0  ...   
...                                                      ...   ...  ...   
261962                                                   NaN  58.0  ...   
262040                                                   NaN  59.0  ...   
262760                                                   NaN  60.0  ...   
262820                                                   NaN  68.0  ...   
264540                                                   NaN  68.0  ...   

           attacking_crossing  attacking_finishing  \
sofifa_id                                            
158023                     85                   95   
188545                     71                   95   
20801                      87                   95   
190871                     85                   83   
192985                     94                   82   
...                       ...            

In [54]:
# column 26: 'weak_foot' (player weak foot attribute)
male_df['weak_foot'].unique()

array([4, 5, 3, 1, 2])

In [55]:
male_df['weak_foot'].isna().sum()

0

In [14]:
male_df[male_df['weak_foot']==1]['player_positions'].value_counts()

GK             106
ST               6
CB               5
LB               4
CDM, CM          2
RB, RWB          2
CB, CDM          2
CM               2
RM, RW           1
CM, CDM          1
RW               1
CB, LB           1
LB, CB           1
RB, CDM          1
LM               1
CM, CAM          1
CAM              1
LB, LWB          1
CM, CDM, LM      1
RB               1
CB, LWB          1
RB, RM           1
LWB, LB, LM      1
RM               1
Name: player_positions, dtype: int64

In [56]:
# column 27: 'skill_moves' (player skill moves attribute)
male_df['skill_moves'].unique()

array([4, 5, 1, 3, 2])

In [57]:
male_df['skill_moves'].isna().sum()

0

In [58]:
# column 28: 'international_reputation' (player international reputation attribute)
male_df['international_reputation'].unique()

array([5, 4, 3, 2, 1])

In [59]:
male_df['international_reputation'].isna().sum()

0

In [60]:
# dropping columns 30, 31, 33, 34: 'body_type', 'real_face', 'player_tags', 'player_traits'
male_df.drop('body_type',axis=1, inplace=True)
male_df.drop('real_face',axis=1, inplace=True)
male_df.drop('player_tags',axis=1, inplace=True)
male_df.drop('player_traits',axis=1, inplace=True)

In [38]:
# column 29: 'work_rate' (player work rate attributes (attacking / defensive))
male_df['work_rate'].unique()

array(['Medium/Low', 'High/Medium', 'High/Low', 'High/High',
       'Medium/Medium', 'Medium/High', 'Low/High', 'Low/Medium',
       'Low/Low'], dtype=object)

In [39]:
male_df['work_rate'].dtype

dtype('O')

In [61]:
# column 32: 'release_clause_eur'(player release clause (in EUR) - if applicable)
male_df['release_clause_eur'].dtype

dtype('float64')

In [62]:
male_df['release_clause_eur'].isna().sum()

1176

In [63]:
male_df['release_clause_eur'].isna().sum() / len(male_df['release_clause_eur'])

0.061125838141275535

In [64]:
male_df['release_clause_eur'] = male_df['release_clause_eur'].fillna(0)

In [65]:
male_df['release_clause_eur'].isna().sum()

0

In [40]:
# column 35: 'pace'(player pace attribute)
male_df['pace'].unique()

array([85., 78., 87., 91., 76., nan, 97., 70., 88., 65., 90., 72., 53.,
       84., 75., 89., 71., 73., 83., 67., 86., 64., 81., 79., 61., 68.,
       56., 63., 42., 50., 82., 93., 80., 66., 92., 77., 55., 95., 58.,
       60., 69., 62., 74., 59., 40., 57., 45., 94., 96., 32., 49., 52.,
       41., 51., 39., 54., 33., 47., 36., 44., 46., 48., 34., 35., 37.,
       43., 38., 30., 31., 28., 29.])

In [46]:
male_df['pace'].isna().sum()

2043

In [66]:
male_df['pace'] = male_df['pace'].fillna(0)

In [67]:
male_df['pace'].isna().sum()

0

In [68]:
# column 35: 'shooting'(player shooting attribute)
male_df['shooting'].unique()

array([92., 94., 83., 86., nan, 88., 91., 66., 87., 73., 60., 70., 90.,
       81., 82., 89., 76., 84., 61., 53., 69., 68., 38., 46., 59., 72.,
       62., 78., 28., 49., 79., 71., 50., 80., 41., 54., 74., 58., 63.,
       85., 75., 67., 55., 35., 77., 45., 65., 25., 64., 51., 43., 42.,
       52., 40., 47., 30., 57., 37., 56., 36., 32., 48., 31., 39., 33.,
       22., 34., 29., 44., 27., 20., 26., 23., 24., 18., 21., 19.])

In [69]:
male_df['shooting'].isna().sum()

2132

In [70]:
male_df['shooting'] = male_df['shooting'].fillna(0)

In [71]:
male_df['passing'].unique()

array([91., 79., 80., 86., 93., nan, 83., 75., 81., 82., 76., 71., 74.,
       89., 65., 67., 87., 85., 88., 60., 77., 90., 51., 64., 70., 78.,
       72., 53., 84., 69., 57., 58., 73., 44., 68., 55., 62., 61., 59.,
       56., 63., 66., 52., 50., 49., 48., 54., 47., 45., 46., 38., 40.,
       43., 39., 41., 35., 42., 36., 37., 34., 33., 31., 32., 29., 28.,
       25., 30., 27.])

In [72]:
male_df['passing'] = male_df['passing'].fillna(0)

In [73]:
male_df['passing'].isna().sum()

0

In [74]:
# column 37: 'dribbling'(player dribbling attribute)
male_df['dribbling'].unique()

array([95., 86., 88., 94., nan, 92., 83., 82., 87., 73., 72., 89., 90.,
       84., 74., 81., 78., 80., 91., 68., 59., 65., 69., 76., 85., 70.,
       79., 77., 58., 66., 62., 67., 63., 64., 71., 61., 51., 75., 57.,
       55., 60., 50., 56., 52., 49., 54., 53., 48., 46., 45., 41., 35.,
       44., 42., 47., 36., 43., 39., 37., 40., 34., 38., 33., 32., 31.,
       30., 28., 29., 27.])

In [75]:
male_df['dribbling'] = male_df['dribbling'].fillna(0)

In [76]:
# column 38: 'defending'(player defending attribute)
male_df['defending'].unique()

array([34., 44., 37., 64., nan, 36., 47., 87., 39., 43., 86., 91., 45.,
       83., 88., 71., 70., 33., 72., 48., 56., 65., 79., 89., 81., 40.,
       82., 77., 80., 38., 46., 52., 85., 30., 54., 78., 51., 35., 73.,
       59., 41., 76., 84., 57., 67., 68., 50., 75., 31., 42., 63., 69.,
       49., 55., 60., 53., 74., 27., 32., 58., 29., 66., 20., 25., 26.,
       61., 24., 28., 23., 22., 62., 19., 21., 18., 16., 17., 14., 15.])

In [77]:
male_df['defending'].isna().sum()

2132

In [78]:
male_df['defending'] = male_df['defending'].fillna(0)

In [79]:
# column 40: 'physic'(player physic attribute)
male_df['physic'].unique()

array([65., 82., 75., 63., 78., nan, 77., 83., 69., 90., 84., 79., 68.,
       66., 88., 71., 67., 81., 86., 60., 76., 72., 85., 45., 73., 80.,
       55., 53., 87., 58., 50., 59., 70., 64., 57., 61., 74., 62., 56.,
       52., 89., 48., 51., 42., 49., 54., 47., 46., 37., 35., 40., 43.,
       41., 39., 44., 34., 38., 36., 33., 31., 32., 29.])

In [80]:
male_df['physic'].isna().sum()

2132

In [81]:
male_df['physic'] = male_df['physic'].fillna(0)

In [82]:
male_df['physic'].isna().sum()

0

In [85]:
male_df.iloc[:,35:51]

defending  physic  attacking_crossing  attacking_finishing  \
sofifa_id                                                               
158023          34.0    65.0                  85                   95   
188545          44.0    82.0                  71                   95   
20801           34.0    75.0                  87                   95   
190871          37.0    63.0                  85                   83   
192985          64.0    78.0                  94                   82   
...              ...     ...                 ...                  ...   
261962          42.0    49.0                  46                   32   
262040          41.0    51.0                  54                   33   
262760          41.0    52.0                  39                   32   
262820          15.0    42.0                  29                   49   
264540          36.0    48.0                  39                   32   

           attacking_heading_accuracy  attacking_short_passing  \
sofifa_id                                                        
158023                             70                       91   
188545                             90                       85   
20801                              90                       80   
190871                             63                       86   
192985                             55                       94   
...                               ...                      ...   
261962                             48                       50   
262040                             46                       51   
262760                             43                       49   
262820                             40                       38   
264540                             46                       50   

           attacking_volleys  skill_dribbling  skill_curve  skill_fk_accuracy  \
sofifa_id                                                                       
158023                    88               96           93                 94   
188545                    89               85           79                 85   
20801                     86               88           81                 84   
190871                    86               95           88                 87   
192985                    82               88           85                 83   
...                      ...              ...          ...                ...   
261962                    30               45           33                 38   
262040                    32               41           53                 31   
262760                    37               47           37                 37   
262820                    34               42           36                 34   
264540                    37               48           38                 32   

           skill_long_passing  skill_ball_control  movement_acceleration  \
sofifa_id                                                                  
158023                     91                  96                     91   
188545                     70                  88                     77   
20801                      77                  88                     85   
190871                     81                  95                     93   
192985                     93                  91                     76   
...                       ...                 ...                    ...   
261962                     48                  49                     56   
262040                     50                  42                     60   
262760                     49                  49                     60   
262820                     33                  45                     69   
264540                     49                  38                     70   

           movement_sprint_speed  movement_agility  movement_reactions  
sofifa_id                                                               
158023       

In [86]:
male_df['attacking_crossing'].unique()

array([85, 71, 87, 94, 13, 78, 15, 18, 80, 68, 75, 14, 83, 58, 53, 79, 20,
       91, 17, 12, 66, 88, 73, 11, 47, 70, 86, 55, 77, 82, 92, 54, 63, 65,
       62, 30, 42, 81, 69, 74, 40, 60, 44, 16, 76, 49, 84, 64, 56, 52, 72,
       57, 22, 51, 35, 45, 24, 50, 67,  9, 27, 25, 59, 10, 46, 38, 19, 36,
       34, 48, 39, 61, 89, 90, 29, 41, 43,  8, 37, 32, 28, 23, 31, 21, 33,
       26,  7,  6])

In [87]:
male_df['attacking_crossing'].isna().sum()

0

In [88]:
male_df['attacking_finishing'].unique()

array([95, 83, 82, 11, 93, 13, 14, 94, 65, 90, 88, 64, 52, 86, 91, 68, 12,
       77, 92, 15, 85, 10, 72, 79, 75, 60, 51, 55, 29, 33, 57, 73, 67, 76,
       22, 46, 81, 89, 63, 45, 42, 40, 78, 48, 80, 84, 25, 50, 54, 16, 34,
       44, 39, 66, 69, 74, 37, 87, 71,  9, 70, 36, 19, 32, 61, 53, 31, 59,
        5, 47, 27, 56, 18, 30, 26, 62, 49,  8, 38, 28, 20, 41, 58, 17, 43,
       24, 35, 21,  6,  7, 23,  4,  3,  2])

In [89]:
male_df['attacking_finishing'].isna().sum()

0

In [90]:
male_df['attacking_heading_accuracy'].unique()

array([70, 90, 63, 55, 15, 72, 25, 11, 86, 54, 89, 13, 68, 79, 87, 84, 59,
       14, 29, 12, 92, 58, 46, 64, 69, 78, 10, 51, 16, 81, 74, 57, 88, 67,
       38, 77, 61, 48, 82, 75, 53, 83, 23, 50, 44, 73, 65, 56, 42, 60, 85,
       40, 21, 49, 66, 71, 26, 36, 52, 43, 76, 17, 47, 80, 39, 62, 19, 35,
       18, 45, 20, 34, 24, 28, 41, 93, 22,  7, 91, 30, 27, 37, 33, 32,  8,
        9, 31,  5,  6])

In [91]:
male_df['attacking_heading_accuracy'].isna().sum()

0

In [92]:
male_df['attacking_short_passing'].unique()

array([91, 85, 80, 86, 94, 43, 60, 61, 82, 33, 84, 79, 87, 45, 36, 83, 93,
       77, 40, 50, 32, 88, 90, 81, 65, 42, 92, 35, 63, 78, 74, 72, 44, 75,
       48, 73, 55, 89, 70, 39, 76, 30, 20, 23, 34, 25, 31, 18, 69, 46, 38,
       37, 17, 71, 27, 24, 67, 62, 66, 28, 26, 22, 68, 51, 29, 11, 56, 54,
       64, 49, 52, 59, 15, 58, 41, 16, 57, 14, 21, 53, 19, 12, 13, 47,  8,
        7])

In [93]:
male_df['attacking_short_passing'].isna().sum()

0

In [94]:
male_df['attacking_volleys'].unique()

array([88, 89, 86, 82, 13, 83, 11, 14, 56, 12, 78, 62, 45, 75, 81, 18, 69,
       20,  8, 90, 67, 87, 85, 76, 84, 64, 35, 32, 70, 61, 60, 44, 72, 74,
       42, 47, 40, 77, 59, 15, 58, 10, 57, 27, 49, 71, 68, 73, 80, 53, 79,
       16, 65, 30, 66, 37, 52, 38, 51,  9, 50, 48, 39, 34, 63, 46, 33, 43,
       23, 31, 17, 28, 24, 54, 41, 19, 36, 55, 22, 25,  5, 21, 29, 26,  6,
        7,  4,  3])

In [95]:
male_df['attacking_volleys'].isna().sum()

0

In [96]:
male_df['skill_dribbling'].unique()

array([96, 85, 88, 95, 12, 93, 30, 21, 83, 79, 87, 13, 69, 70, 90, 23, 27,
       28, 65, 80, 24, 78, 86, 10, 11, 77, 91, 84, 81, 92, 64, 57, 18, 82,
       14, 55, 63, 89, 67, 15, 74, 19, 66, 72, 71, 47, 61, 32, 76, 54, 50,
       62, 68, 16, 60, 58, 59, 20, 73, 43,  9, 56, 75, 51, 22, 53, 52, 26,
       25,  8, 35, 49, 34, 17, 48, 42, 45, 44, 40, 38, 31, 46, 29, 41, 39,
       36,  7, 37, 33,  6,  5,  4])

In [97]:
male_df['skill_dribbling'].isna().sum()

0

In [100]:
male_df.iloc[:,40:51].isna().sum()

attacking_short_passing    0
attacking_volleys          0
skill_dribbling            0
skill_curve                0
skill_fk_accuracy          0
skill_long_passing         0
skill_ball_control         0
movement_acceleration      0
movement_sprint_speed      0
movement_agility           0
movement_reactions         0
dtype: int64